### PR TITLE
Unit 6

### PR DESCRIPTION
**Pull request by Chuckandfecht**
Pull request for completion of Unit 6: AngularJS

### CODE REVIEW

**Comment by rjpepmeyer** [comment]
Looks good, just saw some minor things:
    
1. Readme should say `gulp dev` now instead of `gulp`
2. Some variables in your formatPhoneNumber aren't declared
3. Some emails (e.g. user@example.co.uk) don't show an error, but prevent submission
    
1 and 2 are straight forward, but I might suggest a second opinion on 3. I'm not sure if it's important enough to be concerned with.

**Comment by Chuckandfecht** [comment]
@rjpepmeyer  Fixed 1, which variables aren't being declared in formatPhoneNumber()? Forward is delcared at the start of module.js and a redeclaration pushes it out of scope. If you're reffering to `n`, it's the parameter. Looking in to 3

**Comment by rjpepmeyer** [comment]
Ah, I was looking for `lastlength` and `forward` in `formatPhoneNumber` – missed them at the top of `module.js`.

**Comment by jakekemple** [comment]
Looking good so far. A few things:

1. Starting the server and not being in the dist folder is not necessarily an issue that can be pawned off to .htaccess or other ways of url resolution (Though that is probably possible as a workaround). You should probably just change the server root to the dist folder in your gulpfile (this will break some of your references, which you will need to fix to point to the dist folder as well).

2. Gonna get picky with UX. (Didn't see any explicit rules on these in the wiki, but we were criticized when we did this, so i will at least let you be aware). 
 - No server error should fire without a UI notification. The user should always get some sort of alert for any server error. (I broke it a few ways but did not get an error, with both phone numbers and emails). Fix this with excellent form filters.
 - Also, this is reallly nitpicky, but it is helpful if there is some sort of note indicating that the email cannot be changed. A layperson might think that something is broken to where they cannot change their email, in which they might start complaining or asking questions. It should be explicitly clear that this is purposefully not an option.

Thats it, everything else seems to be functioning clearly. Good progress

**Comment by Chuckandfecht** [comment]
It should now be impossible to make a form throw an error just by typing (or not typing) a value

**Comment by jakekemple** [comment]
When I edit a user's phone number and enter spaces instead of numerals, it will save to the db that way.

I think it's just a small issue: your regex pattern seems to be good for 'Create User', But on Edit User I don't see one.

**Comment by rjpepmeyer** [comment]
Looking good, only thing I noticed was that when I try to create a user with an unexpected TLD in the email, I get `userEditor is not defined` in the console (although everything behaves as expected).

**Comment by jakekemple** [comment]
👍

**Pull request merged**
