### PR TITLE
6.2.2

### PR DESCRIPTION
**Pull request by Chuckandfecht**
Pull request for completion through section 6.2.2 of the UX Intern onboarding project

### CODE REVIEW

**Comment by rjpepmeyer** [comment]
Went through with a fine tooth come and came up with a few suggestions:
     
- When you edit or delete a user, it actually loads the user list before the changes are complete, because it's an asynchronous event. Try wrapping the `$state.go` in a `.then`
- `var angular = angular` is unnecessary in your module. Deleting it doesn't seem to cause any problems.
- The user profile page looks editable. Do the values need to be in inputs? (If so, a simple style change [such as a grey background] would help.)
- Couldn't hurt if the readme mentioned running `node index` from within ux_onboarding
- `users.html` has some odd indents I think you overlooked.
     
Overall, though, it looks great. That's very few suggestions for 15 commits worth of work. Nice job!

**Comment by rjpepmeyer** [comment]
- The user profile and readme look great.
- Your fix for `editUser` works great, but I think you forgot to put it on `deleteUser` too.
- I just noticed: your userProfile controller is in the directives folder (it might make it easier if you name things like "userProfileController.js").

**Comment by rginther** [comment]
I'm getting a few errors:
- A bad PUT request (400) when trying to save an edit for all fields, even though it seems not changing anything and just hitting save redirects back to the page just fine.
- When trying to edit the phone field, I get a undefined 'replace' error (which I believe you mentioned).

Suggestions:
- Seems that I am able to create a user with an email that isn't proper (example@hotmail shouldn't apply to any situation I wouldn't think).
- It seems that editing a phone number eventually auto-formats to a correct format, but when creating a user, the phone number will stay '5555555555'.
- Removing the '#' from the URL would make the url look a lot cleaner.

Other than those things, the changes Ron had mentioned are good. Everything else looks good.

**Comment by rjpepmeyer** [comment]
👍  Looks to me like you're ready to get into unit 6.3 (building into dist). And after that comes unit 6.4, from which you've already made steady progress (polishing up/adding extra features). 💯

**Comment by rginther** [comment]
👍 Looks good to me.

**Pull request merged**
